# Generated by Django 3.2.5 on 2023-05-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('shape', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=200)),
                ('continent', models.CharField(max_length=200)),
                ('capitale', models.CharField(max_length=200)),
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_question', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('continents', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField()),
                ('answer_difficulty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('user', models.CharField(max_length=200)),
                ('device', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.quiz')),
            ],
        ),
    ]
