# Generated by Django 4.2 on 2023-05-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_record_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type_questions',
            field=models.CharField(default='', max_length=400),
        ),
    ]
