# Generated by Django 4.2 on 2023-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_quiz_type_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
