# Generated by Django 4.2 on 2023-05-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
